### PR TITLE
fixes: v9.0.0 fails template creation with ES v7 with ElasticsearchCl…

### PR DESCRIPTION
**Pull request by nenadvicentic**
…ientException #518

Co-authored-by: AlexGoris-KasparSolutions

**What issue does this PR address?**
#518 

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit follows our [guidelines](https://github.com/serilog/serilog/blob/dev/CONTRIBUTING.md)
- [x] Unit Tests for the changes have been added (for bug fixes / features)

### CODE REVIEW

**Comment by nenadvicentic** [comment]
@mivano If you have time, let's merge this hotfix into `master` branch and release `9.0.1` version? We can later merge the fix back to `dev` branch as well. This it can be released immediately.

Fix is based on #519 pull request from [AlexGoris-KasparSolutions](https://github.com/AlexGoris-KasparSolutions), but since he did not reply couple weeks I did modifications I suggested to him and added unit-tests.

**Comment by mivano** [comment]
Merged to master and packages have been generated as version 9.0.1 from master.

**Comment by mivano** [comment]
Thanks @nenadvicentic for picking this up!

**Comment by nenadvicentic** [comment]
@mivano Smoke tested 9.0.1 briefly on Elasticsearch v7. It created default index-template.

**Comment by mivano** [comment]
Super!

**Pull request merged**
