### PR TITLE
Remove support for Elasticsearch v2 and v5.

### PR DESCRIPTION
**Pull request by nenadvicentic**
**What issue does this PR address?**

Since underlying `Elasticsearch.NET` client version `7.17.x` supports only major version 6, 7 and 8 of Elasticsearch server (as it can be seen in the source-code of `RequestPipeline.MinVersion` field [here](https://github.com/elastic/elasticsearch-net/blob/7.17.5/src/Elasticsearch.Net/Transport/Pipeline/RequestPipeline.cs#L34)), we can remove code and tests that supports version 2 and 5.

**Does this PR introduce a breaking change?**
Yes, since index templates for `V2` and `V5` can no longer be selected, but it removes broken functionality.

**Please check if the PR fulfills these requirements**
- [ x] The commit follows our [guidelines](https://github.com/serilog/serilog/blob/dev/CONTRIBUTING.md)
- [ x] Unit Tests for the changes have been added (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by nenadvicentic** [comment]
@mivano Can we merge this pull request too?

I removed v2 and v5 templates, enumeration values and related code, since Elasticsearch.NET client does not support this versions anyway.

Additionally:
- I added underscore rule for private variables in `.editorconfig`, so that built-in VS refactorings follow naming conventions too.
- Resolved GitHub warning due to usage of deprecated `::set-output` command.

**Comment by mivano** [comment]
Merged! Some issue with the pipeline not able to upload results. Not sure why, but let's progress on this.

**Comment by nenadvicentic** [comment]
@mivano Thank you for the support!

This project is first time I am looking in GitHub pipelines, but anyway, I found this warning in the report, just before the error occurs:

> [Run tests and create NuGet package](https://github.com/serilog-contrib/serilog-sinks-elasticsearch/actions/runs/3987640637/jobs/6852600477#step:9:18)
No files were found with the provided path: TestResults-Linux.html. No artifacts will be uploaded.

Could it be related to this issue (about relative vs full paths for `actions/upload-artifacts`)?
https://github.com/actions/upload-artifact/issues/232

**Comment by mivano** [comment]
The last CI build did work, but still the missing file 
image

Maybe the path is changed, as it is generated:
image

**Comment by mivano** [comment]
I changed the path, now it works fine!
image

**Pull request merged**
